src/accounts/urls.py
from django.urls import path
from .views import RegisterView, MyLoginView, DeleteUserView, WelcomeView

from django.contrib.auth import views as auth_views

from django.conf import settings

from django.conf.urls.static import static

app_name = 'account'

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", MyLoginView.as_view(template_name='accounts/login.html'), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("welcome/", WelcomeView.as_view(), name="welcome"),
    path("delete/<int:pk>/", DeleteUserView.as_view(), name="delete"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/core/urls.py
from .views import IndexView
from django.urls import path

from django.conf import settings

from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/learnlg/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('', include('core.urls')),
]

handler404='core.views.error_404'
handler403='core.views.csrf_failure'

src/accounts/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager

# Create your models here.
"""
    The MyUserManager class extends Django's BaseUserManager
    and provides custom methods for creating users and superusers.
"""
class MyUserManager(BaseUserManager):
    def create_user(self, email, firstname, password=None):
        user = self.model(
            email=self.normalize_email(email).lower().strip(),
            firstname=firstname.strip().title()
        )
        user.set_password(password)
        user.save()
        return user
        
    def create_superuser(self, email, firstname, password=None):
        user = self.create_user(email=email, firstname=firstname, password=password)
        user.is_admin = True
        user.is_staff = True
        user.save()
        return user
    
    
"""
    The CustomUser class extends AbstractBaseUser and defines fields for storing user information, as well as methods for checking user permissions. The USERNAME_FIELD is set to email, and the REQUIRED_FIELDS is set to ['firstname'].
"""
class CustomUser(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True, blank=False)
    firstname = models.CharField(max_length=30, blank=False)
    
    is_active = models.BooleanField(default=True, null=False)
    is_staff = models.BooleanField(default=False, null=False)    
    is_admin = models.BooleanField(default=False, null=False)    
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['firstname']
    objects = MyUserManager()
    
    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

src/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ValidationError

from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV3

from django.contrib.auth.forms import AuthenticationForm

from .models import CustomUser

from django import forms


"""
This code defines a UserRegistrationForm class that extends Django's UserCreationForm. It adds an email field and a firstname field, both with custom error messages for the required validation. The Meta class sets the model to the custom CustomUser model and the fields to be used for registration as email and firstname. The form also includes a captcha field using the ReCaptchaField widget. The clean_email method checks if the email already exists in the CustomUser model, and raises a validation error if it does. The clean_firstname method cleans the entered first name by stripping whitespaces and converting it to title case.
"""
class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(error_messages={'required': 'This field is required.'})
    firstname = forms.CharField(error_messages={'required': 'This field is required.'}, max_length=30)

    class Meta:
        model = CustomUser
        fields = ('email', 'firstname')

    captcha = ReCaptchaField(widget=ReCaptchaV3)

    def clean_email(self):
        email = self.cleaned_data['email'].lower().strip()
        if CustomUser.objects.filter(email=email).exists():
            raise ValidationError('Please enter another email address.')
        return email

    def clean_firstname(self):
        firstname = self.cleaned_data['firstname'].strip().title()
        return firstname
    
    

"""
This code defines a LoginForm class that extends Django's AuthenticationForm. It specifies an error message to display if the login fails and sets the model attribute to the custom CustomUser model. The form also includes a captcha field using the ReCaptchaField widget. The clean_username method is implemented to clean the entered username by converting it to lowercase and stripping whitespaces. It also raises a validation error if the email doesn't match any existing CustomUser email.
"""
class LoginForm(AuthenticationForm):
    
    error_messages = {'invalid_login': ('an error has occurred, please try again'),}
    
    model = CustomUser
    captcha = ReCaptchaField(widget=ReCaptchaV3)
    
    def clean_username(self):
        username = self.cleaned_data['username'].lower().strip()
        if not CustomUser.objects.filter(email=username).exists():
            raise ValidationError('Please enter a correct email address.')
        return username

src/accounts/views.py
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect, render
from django.contrib.auth import login
from django.urls import reverse_lazy
from accounts.models import CustomUser
from django.views.generic import CreateView, DeleteView, View
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from accounts.forms import LoginForm, UserRegistrationForm

"""
AuthenticatedUserMixin is a Django class that provides a dispatch function which checks if the currently logged-in user is authenticated. If the user is authenticated, they will have access to the 'account:welcome' view. If not, the function will not redirect the user and they will not have access to the view.
"""
# https://docs.djangoproject.com/fr/4.0/ref/class-based-views/base/#django.views.generic.base.View.dispatch
class AuthenticatedUserMixin:
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('account:welcome')
        return super().dispatch(request, *args, **kwargs)


"""
RegisterView is a class-based view that handles user registration. It uses the UserRegistrationForm form to gather user data and creates a new user object upon successful form submission. The AuthenticatedUserMixin is used to check if the user is already authenticated, in which case the user will be redirected to the welcome page. If the user is not authenticated, the CreateView will handle the creation of a new user object.
"""
class RegisterView(AuthenticatedUserMixin, CreateView):
    form_class = UserRegistrationForm
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('account:welcome')

    def form_valid(self, form):
        response = super().form_valid(form)
        login(self.request, self.object)
        return response
    
    
"""
The MyLoginView class is a custom LoginView class that inherits from AuthenticatedUserMixin and LoginView classes. It defines the template name to use for the login page as 'accounts/login.html' and sets the form class to LoginForm.
"""
class MyLoginView(AuthenticatedUserMixin, LoginView):
    template_name = 'accounts/login.html'
    form_class = LoginForm
    

"""
The DeleteUserView is a login-protected view for deleting a user's account using a CustomUser model. It specifies the confirmation template and a success URL, and limits the deletion to only the current user's account.
"""
@method_decorator(login_required, name='dispatch')
class DeleteUserView(DeleteView):
    model = CustomUser
    template_name = 'accounts/confirm_delete.html'
    success_url = reverse_lazy('core:index')
    
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(id=self.request.user.id)


"""
The WelcomeView class defines a view for a welcome page accessible only to the authenticated user.
The get method displays the user's first name using an HTML template.
"""
@method_decorator(login_required, name='dispatch')
class WelcomeView(View):
    def get(self, request):
        firstname = self.request.user.firstname
        return render(request, 'accounts/welcomepage.html', {'firstname': firstname})

src/accounts/templates/accounts/confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %} LearnLg | Delete My Account{% endblock title %}

{% block content %}

<form method="post" class="flex justify-center items-center flex-col mt-16">
    {% csrf_token %}

    <div class="w-full bg-gray-50 flex flex-col items-center justify-center pt-16">
        <h1 class="text-center text-gray-500 text-3xl font-bold">Are you sure you want
            <br> to delete the your account?</h1>
            <div class="w-1/2 my-16 flex flew-col">
                <input
                  type="submit"
                  value="Yes"
                  class="mr-5 cursor-pointer w-full block bg-red-600 text-white font-semibold rounded-lg px-2 py-2 mt-6"
                />
                <a href="{% url 'account:welcome' %}" class="text-center ml-5 cursor-pointer w-full bg-gray-200 border text-black font-semibold rounded-lg px-2 py-2 mt-6">No</a>
            </div>
    </div>
    
</div>
</form>
{% endblock content %}

src/accounts/templates/accounts/login.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}LearnLg | Login Page {% endblock title %}

{% block content %}


<section class="flex flex-col md:flex-row h-screen items-center">
  <div class="bg-white hidden lg:block w-full md:w-1/2 xl:w-2/3 h-screen">
    <img
      src="https://images.unsplash.com/photo-1550592704-6c76defa9985?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
      alt=""
      class="w-full h-full object-cover"
    />
  </div>

  <div class="bg-white w-full md:max-w-full lg:max-w-full md:w-full xl:w-1/3 h-screen px-6 lg:px-16 xl:px-12 flex items-center justify-center">
    <div class="w-full h-100">
      <h1 class="text-xl text-gray-800 md:text-2xl font-bold leading-tight mt-12">
        Let's login
      </h1>

      <form class="mt-6" action="#" method="POST">
        
        {% if form.errors %}
          <div class="bg-red-100 text-red-800 px-4 py-3 my-2" role="alert">
            {% for field, errors in form.errors.items %}
              {% for error in errors %}
                {% if field == "username" %}
                <p class="text-sm">
                  → <span class="font-bold">Email:</span> {{ error }}
                </p>
                {% elif field == "captcha" %}
                <p class="text-sm">
                  → <span class="font-bold">Captcha:</span> <span>An error has occurred. Are you a human?</span>
                </p>
                {% else %}
                <p class="text-sm">
                  → <span class="font-bold">Password:</span> {{ error }}
                </p>
                {% endif %}
              {% endfor %}
            {% endfor %}
          </div>
        {% endif %}

        {% csrf_token %}
        <div>
          <label class="block text-gray-700">Email Address<span class="text-red-600 font-bold">*</span></label>
          {{form.username}}
        </div>

        <div class="mt-4 ">
          <label class="block text-gray-700">Password<span class="text-red-600 font-bold">*</span></label>
          {{form.password}}
        </div>
        <div>
          {{form.captcha}}
        </div>

        <input
          type="submit"
          value="Login"
          class="cursor-pointer w-full block bg-gray-800 hover:bg-gray-900 duration-150 text-white font-semibold rounded-lg px-4 py-3 mt-6"
        />
      </form>

      <p class="mt-8">
        Need an account?
        <a href="{% url 'account:register' %}" class="text-gray-800 font-semibold"
          >Create an account</a
        >
      </p>
    </div>
  </div>
</section>

<script src="{% static 'js/custom-login.js' %}"></script>

{% endblock content %}

src/accounts/templates/accounts/register.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}LearnLg | Register Page {% endblock title %}

{% block content %}


<section class="flex flex-col md:flex-row h-screen items-center">

  <div class="bg-white hidden lg:block w-full md:w-1/2 xl:w-1/2 h-screen">
    <img
      src="https://images.unsplash.com/photo-1550592704-6c76defa9985?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
      alt=""
      class="w-full h-full object-cover"
    />
  </div>
  
  <div
  class="bg-white w-full lg:max-w-full lg:w-full xl:w-1/2 h-screen px-6 lg:px-16 xl:px-12 flex items-center justify-center">
    <div class="w-full h-100">
      <h1 class="text-xl md:text-2xl font-bold text-gray-800 leading-tight mt-12">
        Create an account
      </h1>

      <form class="mt-6" method="POST">

        {% csrf_token %}


        
        {% if form.errors %}
          <div class="bg-red-100 text-red-800 px-4 py-3 my-2" role="alert">
            {% for field, errors in form.errors.items %}
              {% for error in errors %}
                {% if field == "email" %}
                <p class="text-sm">
                  → <span class="font-bold">Email Adress:</span> {{ error }}
                </p>
                {% elif field == "firstname" %}
                <p class="text-sm">
                  → <span class="font-bold">Firstname:</span> {{ error }}
                </p>
                {% elif field == "password1" %}
                <p class="text-sm">
                  → <span class="font-bold">Password:</span> {{ error }}
                </p>
                {% elif field == "password2" %}
                <p class="text-sm">
                  → <span class="font-bold">Confirm Password:</span> {{ error }}
                </p>
                {% else %}
                <p class="text-sm">
                  → <span class="font-bold">Captcha:</span> <span>An error has occurred. Are you a human?</span>
                </p>
                {% endif %}
              {% endfor %}
            {% endfor %}
          </div>
        {% endif %}

          <div class="flex flex-col sm:flex-row lg:flex-row xl:flex-row w-full items-center box-border">
            <div class="w-full sm:w-1/2 sm:mr-2">
              <label class="block text-gray-700 ml-1">Email Address<span class="text-red-600 font-bold">*</span></label>
              {{form.email}}
            </div>
            <div class="w-full sm:w-1/2 sm:ml-2 mt-2 sm:mt-0">
              <label class="block text-gray-700 ml-1">Firstname<span class="text-red-600 font-bold">*</span></label>
              {{form.firstname}}
            </div>
          </div>

          <div class="flex flex-col sm:flex-row lg:flex-row xl:flex-row w-full items-center box-border sm:mt-2 mb-8">
            <div class="w-full sm:w-1/2 sm:mr-2 mt-2 sm:mt-0">
              <label class="block text-gray-700 ml-1">Password<span class="text-red-600 font-bold">*</span></label>
              {{form.password1}}
            </div>
            <div class="w-full sm:w-1/2 sm:ml-2 mt-2 sm:mt-0">
              <label class="block text-gray-700 ml-1">Confirm Password<span class="text-red-600 font-bold">*</span></label>
              {{form.password2}}
            </div> 
            <div>
              {{form.captcha}}
            </div>
          </div>
          
          <input
          type="submit"
          value="Register"
          class="cursor-pointer w-full block bg-gray-800 hover:bg-gray-900 duration-150 text-white font-semibold rounded-lg px-4 py-3"/>
        </form>

      <p class="my-8">
        You have an account?
        <a href="{% url 'account:login' %}" class="text-gray-800 font-semibold"
          >Let's login</a
        >
      </p>
    </div>
  </div>

  
</section>

<script src="{% static 'js/custom-register.js' %}"></script>

{% endblock content %}

src/accounts/templates/accounts/welcomepage.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}LearnLg | Welcome {% endblock title %}

{% block content %}

<section class="flex flex-col justify-center h-screen items-center text-gray-500 font-semibold mx-6">

    <nav class="mt-9 flex flex-col w-full justify-end items-end mb-8">
        <a href="{% url 'account:logout' %}" class="text-gray-800 hover:bg-gray-300 border font-semibold duration-150 bg-gray-200 p-3 mx-12 rounded-lg text-sm my-12">Log out</a>
    </nav>

    <h1 class="text-3xl text-gray-500 font-semibold">Welcome <span class="font-bold text-red-500">{{ user.firstname }}</span> 👋!</h1>

    <div class="flex flex-col justify-center items-start">
        <p class=" mt-16">Congratulations, you have succeeded in deploying locally 👌!</p>
        <br><br>
        <p class="">This is only one part of the project. <br> This part includes the following points:</p>
        <br>
        <ul class="text-sm">
            <li>
                → Account creation
            </li>
            <li>
                → Log in
            </li>
            <li>
                → Log out
            </li>
            <li>
                → Delete account
            </li>
            <li>
                → Setting up a custom file for 404 and 403 errors<br>
            </li>
        </ul>
        <br><br>
        <p>See the complete project: <a href="https://learnlg.pythonanywhere.com/" target="_blank" class="text-red-500">LearnLg</a></p>
    </div>
    <div class="flex justify-between items-center mt-4" style="width: 300px;">
        <a class="font-semibold text-gray-800 p-4 bg-gray-200 rounded-lg hover:bg-gray-300 duration-150 mr-7" target="_blank" href="https://christophekadjo.com">Portfolio</a>
        <a href="{% url 'account:delete' user.id %}" class="bg-red-600 font-semibold text-sm text-white ml-6 p-4 rounded-lg hover:bg-red-700 duration-150 ml-7">Delete account</a>
    </div>
    
  
</section>


{% endblock content %}